### ISSUE TITLE
true and false shouldn't be valid Python

### ISSUE THREAD

**Issue by dideler** [differentmatt/filbert#50]
In filbert, `True` and `true` in Python both get evaluated to `true;` in JS.
Similarly, `False` and `false` evaluate to `false;` in JS.

Only `True` and `False` should work. Python would consider `true` and `false` variables, and if they weren't defined beforehand, calling them would result in a NameError. E.g.
```
NameError: name 'true' is not defined
```

Remembering that Python booleans are titleized is another learning block, so this bug may give new programmers a less frustrating experience (avoids moments like "why isn't my if statement working?") but it also teaches them incorrect Python. Just something to consider.

**Comment by dzhang314** [comment]
On a related note, `str(True)` and `str(False)` ought to return `"True"` and `"False"`, not `"true"` and `"false"`.

**Comment by nwinter** [comment]
Fixed with @basicer's new Esper interpreter.
