### ISSUE TITLE
Speed up conversion to dicts/lists

### ISSUE THREAD

**Issue by nwinter** [differentmatt/filbert#58]
I could be wrong, but I think conversion to dicts/lists (which has shown to take a decent amount of time in my profiling) could be sped up. [All these functions we're defining here](https://github.com/differentmatt/filbert/blob/master/filbert.js#L2728-L3048) could probably be just defined once and then referenced when we convert a new native type, instead of being redefined every time we make a native type.

It's not a huge performance killer compared to other stuff I'm investigating now, but some day we should get it.

**Comment by nwinter** [comment]
@basicer I wonder if this is related to any Python performance issues we have been seeing in the new interpreter?

**Comment by basicer** [comment]
You are correct.  They were very slow. I already refactored this in the newest version of filbert. =]
