### ISSUE TITLE
Accepting 'throw' as variable name

### ISSUE THREAD

**Issue by ChristianKleineidam** [differentmatt/filbert#61]
In python it's possible to call a variable throw. Unfortunately it's a reserved word in Javascript, so the code that calls a variable throw crashes. Given that the parser should get valid python code to run I suggest that it renames I valid python variables names like throw that are invalid Javascript variable names into throw1345 or something similar.

**Comment by nwinter** [comment]
Fixed with @basicer's new Esper interpreter.
