### ISSUE TITLE
int() rounds negative numbers in the wrong direction

### ISSUE THREAD

**Issue by dzhang314** [differentmatt/filbert#68]
```python
int(-2.5) # produces -2, should be -3
```
`int()` should always round down, but currently appears to round toward zero.

**Comment by Xavion3** [comment]
No actually this behaviour is correct, int should truncate towards zero and not round down. So rounding towards zero is right for python.

**Comment by dzhang314** [comment]
Oops, looks like I was mistaken about this one. Thanks, I'll close the issue.

**Comment by kyay** [comment]
j
