### ISSUE TITLE
npm version is out of date

### ISSUE THREAD

**Issue by giles-v** [differentmatt/filbert#93]
The code in npm is about 6 years old. Could you republish this module?

**Comment by differentmatt** [comment]
There haven't been many updates since last publish.  Which updates did you need to be published?

**Comment by giles-v** [comment]
I appreciate the response. The published version actually works for me, so I'm going to close this. I thought I was getting different outputs compared to your example page, and noticed that the npm edition differed to the web-served one; but the outcomes I were seeing were just about the differences between `parse` and `parse_dammit`.
